### ISSUE TITLE
Is this a combobox?

### ISSUE THREAD

**Issue by stevecoh1** [cchantep/bootstrap-combobox#2]
Sorry, but this is not a combobox, at least not as the term was originally defined.

A combobox was originally designed as a widget that was a COMBINATION of a text input box and a droplist, so that the user could EITHER pick from a predefined list or enter something else.  This seems to be just a javascript droplist.  There is no provision for entering text not in the list.  That is what I was looking for when I searched for "Bootstrap combobox" and this does not deliver that.

**Comment by cchantep** [comment]
Please be constructive.
